/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7-dev at Wed Jun 22 16:57:50 2016. */

#include "temperature.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t temperature_Temperature_fields[3] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, temperature_Temperature, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, temperature_Temperature, celsius, timestamp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
